// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// runbioclimCpp
Rcpp::List runbioclimCpp(Rcpp::NumericVector Tz, Rcpp::NumericVector soilm, std::vector<bool> out, Rcpp::IntegerVector wetq, Rcpp::IntegerVector dryq, Rcpp::IntegerVector hotq, Rcpp::IntegerVector colq);
RcppExport SEXP _microclimf_runbioclimCpp(SEXP TzSEXP, SEXP soilmSEXP, SEXP outSEXP, SEXP wetqSEXP, SEXP dryqSEXP, SEXP hotqSEXP, SEXP colqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Tz(TzSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type soilm(soilmSEXP);
    Rcpp::traits::input_parameter< std::vector<bool> >::type out(outSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type wetq(wetqSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dryq(dryqSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hotq(hotqSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type colq(colqSEXP);
    rcpp_result_gen = Rcpp::wrap(runbioclimCpp(Tz, soilm, out, wetq, dryq, hotq, colq));
    return rcpp_result_gen;
END_RCPP
}
// runmicro1Cpp
Rcpp::List runmicro1Cpp(Rcpp::DataFrame obstime, Rcpp::DataFrame climdata, Rcpp::List vegp, Rcpp::List soilc, Rcpp::NumericMatrix lats, Rcpp::NumericMatrix lons, Rcpp::NumericVector zref, double z, Rcpp::NumericVector ufRef, Rcpp::NumericVector HRef, Rcpp::NumericVector dRef, Rcpp::NumericVector zmRef, Rcpp::NumericVector shelterc);
RcppExport SEXP _microclimf_runmicro1Cpp(SEXP obstimeSEXP, SEXP climdataSEXP, SEXP vegpSEXP, SEXP soilcSEXP, SEXP latsSEXP, SEXP lonsSEXP, SEXP zrefSEXP, SEXP zSEXP, SEXP ufRefSEXP, SEXP HRefSEXP, SEXP dRefSEXP, SEXP zmRefSEXP, SEXP sheltercSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type obstime(obstimeSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type climdata(climdataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type vegp(vegpSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type soilc(soilcSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lons(lonsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type zref(zrefSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ufRef(ufRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type HRef(HRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dRef(dRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type zmRef(zmRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type shelterc(sheltercSEXP);
    rcpp_result_gen = Rcpp::wrap(runmicro1Cpp(obstime, climdata, vegp, soilc, lats, lons, zref, z, ufRef, HRef, dRef, zmRef, shelterc));
    return rcpp_result_gen;
END_RCPP
}
// dampingDepthGridCpp
Rcpp::NumericVector dampingDepthGridCpp(Rcpp::NumericMatrix Vq, Rcpp::NumericMatrix Vm, Rcpp::NumericMatrix Vo, Rcpp::NumericMatrix Mc, Rcpp::NumericMatrix thetaS, Rcpp::NumericMatrix psie, Rcpp::NumericMatrix b, Rcpp::NumericVector soilm, Rcpp::NumericVector Ts, Rcpp::NumericVector pk);
RcppExport SEXP _microclimf_dampingDepthGridCpp(SEXP VqSEXP, SEXP VmSEXP, SEXP VoSEXP, SEXP McSEXP, SEXP thetaSSEXP, SEXP psieSEXP, SEXP bSEXP, SEXP soilmSEXP, SEXP TsSEXP, SEXP pkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Vq(VqSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Vm(VmSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Vo(VoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Mc(McSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type thetaS(thetaSSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type psie(psieSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type soilm(soilmSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ts(TsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pk(pkSEXP);
    rcpp_result_gen = Rcpp::wrap(dampingDepthGridCpp(Vq, Vm, Vo, Mc, thetaS, psie, b, soilm, Ts, pk));
    return rcpp_result_gen;
END_RCPP
}
// soilWaterPotentialGridCpp
Rcpp::NumericVector soilWaterPotentialGridCpp(Rcpp::NumericMatrix thetaS, Rcpp::NumericMatrix psie, Rcpp::NumericMatrix b, Rcpp::NumericVector soilm);
RcppExport SEXP _microclimf_soilWaterPotentialGridCpp(SEXP thetaSSEXP, SEXP psieSEXP, SEXP bSEXP, SEXP soilmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type thetaS(thetaSSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type psie(psieSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type soilm(soilmSEXP);
    rcpp_result_gen = Rcpp::wrap(soilWaterPotentialGridCpp(thetaS, psie, b, soilm));
    return rcpp_result_gen;
END_RCPP
}
// surfaceResistGridCpp
Rcpp::List surfaceResistGridCpp(Rcpp::List rad, Rcpp::List clim, Rcpp::NumericVector soilm, Rcpp::List soil, Rcpp::List veg, Rcpp::List ref);
RcppExport SEXP _microclimf_surfaceResistGridCpp(SEXP radSEXP, SEXP climSEXP, SEXP soilmSEXP, SEXP soilSEXP, SEXP vegSEXP, SEXP refSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type rad(radSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type clim(climSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type soilm(soilmSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type soil(soilSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type veg(vegSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type ref(refSEXP);
    rcpp_result_gen = Rcpp::wrap(surfaceResistGridCpp(rad, clim, soilm, soil, veg, ref));
    return rcpp_result_gen;
END_RCPP
}
// referenceGroundResistCpp
Rcpp::NumericVector referenceGroundResistCpp(Rcpp::NumericVector uref, Rcpp::NumericVector ufRef, Rcpp::NumericVector HRef, Rcpp::NumericVector Ta, Rcpp::NumericVector pk, double zref, double hRef, double paiRef);
RcppExport SEXP _microclimf_referenceGroundResistCpp(SEXP urefSEXP, SEXP ufRefSEXP, SEXP HRefSEXP, SEXP TaSEXP, SEXP pkSEXP, SEXP zrefSEXP, SEXP hRefSEXP, SEXP paiRefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type uref(urefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ufRef(ufRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type HRef(HRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ta(TaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< double >::type zref(zrefSEXP);
    Rcpp::traits::input_parameter< double >::type hRef(hRefSEXP);
    Rcpp::traits::input_parameter< double >::type paiRef(paiRefSEXP);
    rcpp_result_gen = Rcpp::wrap(referenceGroundResistCpp(uref, ufRef, HRef, Ta, pk, zref, hRef, paiRef));
    return rcpp_result_gen;
END_RCPP
}
// soilmDistributeCpp
Rcpp::NumericVector soilmDistributeCpp(Rcpp::NumericMatrix Smin, Rcpp::NumericMatrix Smax, Rcpp::NumericMatrix tadd, Rcpp::NumericMatrix wet, Rcpp::NumericVector theta0, int tsteps);
RcppExport SEXP _microclimf_soilmDistributeCpp(SEXP SminSEXP, SEXP SmaxSEXP, SEXP taddSEXP, SEXP wetSEXP, SEXP theta0SEXP, SEXP tstepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Smin(SminSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Smax(SmaxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type tadd(taddSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type wet(wetSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< int >::type tsteps(tstepsSEXP);
    rcpp_result_gen = Rcpp::wrap(soilmDistributeCpp(Smin, Smax, tadd, wet, theta0, tsteps));
    return rcpp_result_gen;
END_RCPP
}
// groundHeatFluxCpp
Rcpp::List groundHeatFluxCpp(Rcpp::NumericVector RabsGround, Rcpp::NumericVector rGz, Rcpp::NumericVector rGm, Rcpp::NumericVector RabsCanopy, Rcpp::NumericVector rHa, Rcpp::NumericVector rSurf_ref, Rcpp::NumericVector hSurf_ref, Rcpp::NumericVector hFol_ref, Rcpp::NumericVector soilm, Rcpp::NumericVector Ta, Rcpp::NumericVector rh, Rcpp::NumericVector pk, Rcpp::NumericMatrix Vq, Rcpp::NumericMatrix Vm, Rcpp::NumericMatrix Vo, Rcpp::NumericMatrix Mc, Rcpp::NumericMatrix thetaS, Rcpp::NumericMatrix psie, Rcpp::NumericMatrix b, Rcpp::NumericMatrix svfa, Rcpp::NumericVector emGround, Rcpp::NumericVector emCanopy, Rcpp::NumericMatrix slope, Rcpp::NumericMatrix aspect, Rcpp::NumericVector Rsw, Rcpp::NumericVector Rdif, Rcpp::NumericMatrix lats, Rcpp::NumericMatrix lons, Rcpp::IntegerVector year, Rcpp::IntegerVector month, Rcpp::IntegerVector day, Rcpp::NumericVector hour, Rcpp::NumericVector G_ref, Rcpp::NumericVector RabsGround_ref, Rcpp::NumericVector rGz_ref, Rcpp::NumericVector theta0_ref, Rcpp::NumericVector emGround_ref, Rcpp::NumericVector VqRef, Rcpp::NumericVector VmRef, Rcpp::NumericVector VoRef, Rcpp::NumericVector McRef, Rcpp::NumericVector thetaSRef, Rcpp::NumericVector psieRef, Rcpp::NumericVector bRef);
RcppExport SEXP _microclimf_groundHeatFluxCpp(SEXP RabsGroundSEXP, SEXP rGzSEXP, SEXP rGmSEXP, SEXP RabsCanopySEXP, SEXP rHaSEXP, SEXP rSurf_refSEXP, SEXP hSurf_refSEXP, SEXP hFol_refSEXP, SEXP soilmSEXP, SEXP TaSEXP, SEXP rhSEXP, SEXP pkSEXP, SEXP VqSEXP, SEXP VmSEXP, SEXP VoSEXP, SEXP McSEXP, SEXP thetaSSEXP, SEXP psieSEXP, SEXP bSEXP, SEXP svfaSEXP, SEXP emGroundSEXP, SEXP emCanopySEXP, SEXP slopeSEXP, SEXP aspectSEXP, SEXP RswSEXP, SEXP RdifSEXP, SEXP latsSEXP, SEXP lonsSEXP, SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP, SEXP hourSEXP, SEXP G_refSEXP, SEXP RabsGround_refSEXP, SEXP rGz_refSEXP, SEXP theta0_refSEXP, SEXP emGround_refSEXP, SEXP VqRefSEXP, SEXP VmRefSEXP, SEXP VoRefSEXP, SEXP McRefSEXP, SEXP thetaSRefSEXP, SEXP psieRefSEXP, SEXP bRefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type RabsGround(RabsGroundSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rGz(rGzSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rGm(rGmSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type RabsCanopy(RabsCanopySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rHa(rHaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rSurf_ref(rSurf_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hSurf_ref(hSurf_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hFol_ref(hFol_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type soilm(soilmSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ta(TaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Vq(VqSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Vm(VmSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Vo(VoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Mc(McSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type thetaS(thetaSSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type psie(psieSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type svfa(svfaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type emGround(emGroundSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type emCanopy(emCanopySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type aspect(aspectSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Rsw(RswSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Rdif(RdifSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lons(lonsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type year(yearSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type month(monthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type day(daySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hour(hourSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type G_ref(G_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type RabsGround_ref(RabsGround_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rGz_ref(rGz_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta0_ref(theta0_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type emGround_ref(emGround_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type VqRef(VqRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type VmRef(VmRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type VoRef(VoRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type McRef(McRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type thetaSRef(thetaSRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type psieRef(psieRefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type bRef(bRefSEXP);
    rcpp_result_gen = Rcpp::wrap(groundHeatFluxCpp(RabsGround, rGz, rGm, RabsCanopy, rHa, rSurf_ref, hSurf_ref, hFol_ref, soilm, Ta, rh, pk, Vq, Vm, Vo, Mc, thetaS, psie, b, svfa, emGround, emCanopy, slope, aspect, Rsw, Rdif, lats, lons, year, month, day, hour, G_ref, RabsGround_ref, rGz_ref, theta0_ref, emGround_ref, VqRef, VmRef, VoRef, McRef, thetaSRef, psieRef, bRef));
    return rcpp_result_gen;
END_RCPP
}
// belowGroundShortcutCpp
Rcpp::NumericVector belowGroundShortcutCpp(Rcpp::NumericVector Ts_est, Rcpp::NumericVector Tgp_ref, Rcpp::NumericVector Tbp_ref, Rcpp::NumericVector DD, Rcpp::NumericVector mat, double reqhgt, double hiy);
RcppExport SEXP _microclimf_belowGroundShortcutCpp(SEXP Ts_estSEXP, SEXP Tgp_refSEXP, SEXP Tbp_refSEXP, SEXP DDSEXP, SEXP matSEXP, SEXP reqhgtSEXP, SEXP hiySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ts_est(Ts_estSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Tgp_ref(Tgp_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Tbp_ref(Tbp_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type DD(DDSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type reqhgt(reqhgtSEXP);
    Rcpp::traits::input_parameter< double >::type hiy(hiySEXP);
    rcpp_result_gen = Rcpp::wrap(belowGroundShortcutCpp(Ts_est, Tgp_ref, Tbp_ref, DD, mat, reqhgt, hiy));
    return rcpp_result_gen;
END_RCPP
}
// canopyTempCpp
Rcpp::NumericVector canopyTempCpp(Rcpp::NumericVector RabsCanopy, Rcpp::NumericVector rHa, Rcpp::NumericVector G_est, Rcpp::NumericVector Ta, Rcpp::NumericVector rh, Rcpp::NumericVector pk, Rcpp::NumericMatrix svfa, Rcpp::NumericVector emCanopy, Rcpp::NumericVector rSurf_ref, Rcpp::NumericVector hSurf_ref);
RcppExport SEXP _microclimf_canopyTempCpp(SEXP RabsCanopySEXP, SEXP rHaSEXP, SEXP G_estSEXP, SEXP TaSEXP, SEXP rhSEXP, SEXP pkSEXP, SEXP svfaSEXP, SEXP emCanopySEXP, SEXP rSurf_refSEXP, SEXP hSurf_refSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type RabsCanopy(RabsCanopySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rHa(rHaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type G_est(G_estSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ta(TaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type svfa(svfaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type emCanopy(emCanopySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rSurf_ref(rSurf_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hSurf_ref(hSurf_refSEXP);
    rcpp_result_gen = Rcpp::wrap(canopyTempCpp(RabsCanopy, rHa, G_est, Ta, rh, pk, svfa, emCanopy, rSurf_ref, hSurf_ref));
    return rcpp_result_gen;
END_RCPP
}
// leafTempCpp
Rcpp::NumericVector leafTempCpp(Rcpp::NumericVector radLpar, Rcpp::NumericVector radLsw, Rcpp::NumericVector radLlw, Rcpp::NumericVector uz, Rcpp::NumericVector Ta, Rcpp::NumericVector rh, Rcpp::NumericVector pk, Rcpp::NumericVector Ca, Rcpp::NumericVector psi_r, Rcpp::NumericMatrix hgt, Rcpp::NumericMatrix pai, Rcpp::NumericMatrix Vcmax25, Rcpp::NumericMatrix Tup, Rcpp::NumericMatrix Tlw, Rcpp::NumericMatrix Dcrit, Rcpp::NumericMatrix alpha, Rcpp::NumericMatrix f0, Rcpp::NumericMatrix fd, Rcpp::NumericMatrix psi50, Rcpp::NumericMatrix apsi, Rcpp::NumericMatrix rpmin, Rcpp::NumericMatrix leafd, Rcpp::LogicalMatrix isC3, double reqhgt);
RcppExport SEXP _microclimf_leafTempCpp(SEXP radLparSEXP, SEXP radLswSEXP, SEXP radLlwSEXP, SEXP uzSEXP, SEXP TaSEXP, SEXP rhSEXP, SEXP pkSEXP, SEXP CaSEXP, SEXP psi_rSEXP, SEXP hgtSEXP, SEXP paiSEXP, SEXP Vcmax25SEXP, SEXP TupSEXP, SEXP TlwSEXP, SEXP DcritSEXP, SEXP alphaSEXP, SEXP f0SEXP, SEXP fdSEXP, SEXP psi50SEXP, SEXP apsiSEXP, SEXP rpminSEXP, SEXP leafdSEXP, SEXP isC3SEXP, SEXP reqhgtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type radLpar(radLparSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type radLsw(radLswSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type radLlw(radLlwSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type uz(uzSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ta(TaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ca(CaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type psi_r(psi_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type hgt(hgtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Vcmax25(Vcmax25SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Tup(TupSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Tlw(TlwSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Dcrit(DcritSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type f0(f0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type fd(fdSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type psi50(psi50SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type apsi(apsiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type rpmin(rpminSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type leafd(leafdSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type isC3(isC3SEXP);
    Rcpp::traits::input_parameter< double >::type reqhgt(reqhgtSEXP);
    rcpp_result_gen = Rcpp::wrap(leafTempCpp(radLpar, radLsw, radLlw, uz, Ta, rh, pk, Ca, psi_r, hgt, pai, Vcmax25, Tup, Tlw, Dcrit, alpha, f0, fd, psi50, apsi, rpmin, leafd, isC3, reqhgt));
    return rcpp_result_gen;
END_RCPP
}
// longwaveGridCpp
Rcpp::List longwaveGridCpp(Rcpp::NumericVector Ts_est, Rcpp::NumericVector Tcanopy_est, Rcpp::NumericVector Ta, Rcpp::NumericMatrix hgt, Rcpp::NumericMatrix pai, Rcpp::NumericMatrix paia, Rcpp::NumericMatrix svfa, Rcpp::NumericVector lwdown, double reqhgt);
RcppExport SEXP _microclimf_longwaveGridCpp(SEXP Ts_estSEXP, SEXP Tcanopy_estSEXP, SEXP TaSEXP, SEXP hgtSEXP, SEXP paiSEXP, SEXP paiaSEXP, SEXP svfaSEXP, SEXP lwdownSEXP, SEXP reqhgtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ts_est(Ts_estSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Tcanopy_est(Tcanopy_estSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ta(TaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type hgt(hgtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type paia(paiaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type svfa(svfaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lwdown(lwdownSEXP);
    Rcpp::traits::input_parameter< double >::type reqhgt(reqhgtSEXP);
    rcpp_result_gen = Rcpp::wrap(longwaveGridCpp(Ts_est, Tcanopy_est, Ta, hgt, pai, paia, svfa, lwdown, reqhgt));
    return rcpp_result_gen;
END_RCPP
}
// aboveCanopyProfileGridCpp
Rcpp::List aboveCanopyProfileGridCpp(Rcpp::NumericVector Tcanopy_est, Rcpp::NumericVector rHa, Rcpp::NumericVector L, Rcpp::NumericVector uf, Rcpp::NumericMatrix d, Rcpp::NumericMatrix zh, Rcpp::NumericVector Ta, Rcpp::NumericVector rh, Rcpp::NumericVector rSurf_ref, Rcpp::NumericVector hSurf_ref, Rcpp::NumericVector rGz, Rcpp::NumericVector rGreq, Rcpp::NumericMatrix zs, double reqhgt, double zref);
RcppExport SEXP _microclimf_aboveCanopyProfileGridCpp(SEXP Tcanopy_estSEXP, SEXP rHaSEXP, SEXP LSEXP, SEXP ufSEXP, SEXP dSEXP, SEXP zhSEXP, SEXP TaSEXP, SEXP rhSEXP, SEXP rSurf_refSEXP, SEXP hSurf_refSEXP, SEXP rGzSEXP, SEXP rGreqSEXP, SEXP zsSEXP, SEXP reqhgtSEXP, SEXP zrefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Tcanopy_est(Tcanopy_estSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rHa(rHaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type uf(ufSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type zh(zhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ta(TaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rSurf_ref(rSurf_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hSurf_ref(hSurf_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rGz(rGzSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rGreq(rGreqSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type zs(zsSEXP);
    Rcpp::traits::input_parameter< double >::type reqhgt(reqhgtSEXP);
    Rcpp::traits::input_parameter< double >::type zref(zrefSEXP);
    rcpp_result_gen = Rcpp::wrap(aboveCanopyProfileGridCpp(Tcanopy_est, rHa, L, uf, d, zh, Ta, rh, rSurf_ref, hSurf_ref, rGz, rGreq, zs, reqhgt, zref));
    return rcpp_result_gen;
END_RCPP
}
// belowCanopyProfileGridCpp
Rcpp::List belowCanopyProfileGridCpp(Rcpp::NumericVector Tcanopy_est, Rcpp::NumericVector Ts_est, Rcpp::NumericVector rBL, Rcpp::NumericVector rGh, Rcpp::NumericVector rGm, Rcpp::NumericVector rGz, Rcpp::NumericMatrix shapeR, Rcpp::NumericMatrix shapeC, Rcpp::NumericMatrix hgtCell, Rcpp::NumericMatrix paiCell, Rcpp::NumericVector Ta, Rcpp::NumericVector rh, Rcpp::NumericVector pk, Rcpp::NumericVector rSurf_ref, Rcpp::NumericVector hSurf_ref, double reqhgt, double zref);
RcppExport SEXP _microclimf_belowCanopyProfileGridCpp(SEXP Tcanopy_estSEXP, SEXP Ts_estSEXP, SEXP rBLSEXP, SEXP rGhSEXP, SEXP rGmSEXP, SEXP rGzSEXP, SEXP shapeRSEXP, SEXP shapeCSEXP, SEXP hgtCellSEXP, SEXP paiCellSEXP, SEXP TaSEXP, SEXP rhSEXP, SEXP pkSEXP, SEXP rSurf_refSEXP, SEXP hSurf_refSEXP, SEXP reqhgtSEXP, SEXP zrefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Tcanopy_est(Tcanopy_estSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ts_est(Ts_estSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rBL(rBLSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rGh(rGhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rGm(rGmSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rGz(rGzSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type shapeR(shapeRSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type shapeC(shapeCSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type hgtCell(hgtCellSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type paiCell(paiCellSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ta(TaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rSurf_ref(rSurf_refSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hSurf_ref(hSurf_refSEXP);
    Rcpp::traits::input_parameter< double >::type reqhgt(reqhgtSEXP);
    Rcpp::traits::input_parameter< double >::type zref(zrefSEXP);
    rcpp_result_gen = Rcpp::wrap(belowCanopyProfileGridCpp(Tcanopy_est, Ts_est, rBL, rGh, rGm, rGz, shapeR, shapeC, hgtCell, paiCell, Ta, rh, pk, rSurf_ref, hSurf_ref, reqhgt, zref));
    return rcpp_result_gen;
END_RCPP
}
// belowCanopyProfilePointCpp
Rcpp::List belowCanopyProfilePointCpp(Rcpp::NumericVector Tcanopy, Rcpp::NumericVector Tground, Rcpp::NumericVector groundhr, Rcpp::NumericVector rBL, Rcpp::NumericVector L, Rcpp::NumericVector uf, double d, double zm, double hgt, double pai, Rcpp::NumericVector Ta, Rcpp::NumericVector rh, Rcpp::NumericVector pk, Rcpp::NumericVector rSurf, Rcpp::NumericVector hSurf, double reqhgt, double zref);
RcppExport SEXP _microclimf_belowCanopyProfilePointCpp(SEXP TcanopySEXP, SEXP TgroundSEXP, SEXP groundhrSEXP, SEXP rBLSEXP, SEXP LSEXP, SEXP ufSEXP, SEXP dSEXP, SEXP zmSEXP, SEXP hgtSEXP, SEXP paiSEXP, SEXP TaSEXP, SEXP rhSEXP, SEXP pkSEXP, SEXP rSurfSEXP, SEXP hSurfSEXP, SEXP reqhgtSEXP, SEXP zrefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Tcanopy(TcanopySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Tground(TgroundSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type groundhr(groundhrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rBL(rBLSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type uf(ufSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type zm(zmSEXP);
    Rcpp::traits::input_parameter< double >::type hgt(hgtSEXP);
    Rcpp::traits::input_parameter< double >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ta(TaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pk(pkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rSurf(rSurfSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hSurf(hSurfSEXP);
    Rcpp::traits::input_parameter< double >::type reqhgt(reqhgtSEXP);
    Rcpp::traits::input_parameter< double >::type zref(zrefSEXP);
    rcpp_result_gen = Rcpp::wrap(belowCanopyProfilePointCpp(Tcanopy, Tground, groundhr, rBL, L, uf, d, zm, hgt, pai, Ta, rh, pk, rSurf, hSurf, reqhgt, zref));
    return rcpp_result_gen;
END_RCPP
}
// computeSolarSeriesRCpp
Rcpp::List computeSolarSeriesRCpp(double lat, double lon, Rcpp::IntegerVector year, Rcpp::IntegerVector month, Rcpp::IntegerVector day, Rcpp::NumericVector hour);
RcppExport SEXP _microclimf_computeSolarSeriesRCpp(SEXP latSEXP, SEXP lonSEXP, SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP, SEXP hourSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type year(yearSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type month(monthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type day(daySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hour(hourSEXP);
    rcpp_result_gen = Rcpp::wrap(computeSolarSeriesRCpp(lat, lon, year, month, day, hour));
    return rcpp_result_gen;
END_RCPP
}
// radiationPointCpp
Rcpp::List radiationPointCpp(double pai, double paia, double x, double lref, double ltra, double clump, double gref, double svfa, double slope, double aspect, Rcpp::NumericVector zend, Rcpp::NumericVector azid, Rcpp::NumericVector shadow, Rcpp::NumericVector Rsw, Rcpp::NumericVector Rdif);
RcppExport SEXP _microclimf_radiationPointCpp(SEXP paiSEXP, SEXP paiaSEXP, SEXP xSEXP, SEXP lrefSEXP, SEXP ltraSEXP, SEXP clumpSEXP, SEXP grefSEXP, SEXP svfaSEXP, SEXP slopeSEXP, SEXP aspectSEXP, SEXP zendSEXP, SEXP azidSEXP, SEXP shadowSEXP, SEXP RswSEXP, SEXP RdifSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< double >::type paia(paiaSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lref(lrefSEXP);
    Rcpp::traits::input_parameter< double >::type ltra(ltraSEXP);
    Rcpp::traits::input_parameter< double >::type clump(clumpSEXP);
    Rcpp::traits::input_parameter< double >::type gref(grefSEXP);
    Rcpp::traits::input_parameter< double >::type svfa(svfaSEXP);
    Rcpp::traits::input_parameter< double >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< double >::type aspect(aspectSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type zend(zendSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type azid(azidSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type shadow(shadowSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Rsw(RswSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Rdif(RdifSEXP);
    rcpp_result_gen = Rcpp::wrap(radiationPointCpp(pai, paia, x, lref, ltra, clump, gref, svfa, slope, aspect, zend, azid, shadow, Rsw, Rdif));
    return rcpp_result_gen;
END_RCPP
}
// splineFitCpp
Rcpp::List splineFitCpp(Rcpp::NumericVector knotX, Rcpp::NumericMatrix knotY);
RcppExport SEXP _microclimf_splineFitCpp(SEXP knotXSEXP, SEXP knotYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type knotX(knotXSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type knotY(knotYSEXP);
    rcpp_result_gen = Rcpp::wrap(splineFitCpp(knotX, knotY));
    return rcpp_result_gen;
END_RCPP
}
// splineEvalCpp
Rcpp::NumericVector splineEvalCpp(Rcpp::List fit, double queryX);
RcppExport SEXP _microclimf_splineEvalCpp(SEXP fitSEXP, SEXP queryXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< double >::type queryX(queryXSEXP);
    rcpp_result_gen = Rcpp::wrap(splineEvalCpp(fit, queryX));
    return rcpp_result_gen;
END_RCPP
}
// BigLeafCpp
Rcpp::DataFrame BigLeafCpp(Rcpp::NumericVector year, Rcpp::NumericVector month, Rcpp::NumericVector day, Rcpp::NumericVector hour, Rcpp::NumericVector temp, Rcpp::NumericVector relhum, Rcpp::NumericVector pres, Rcpp::NumericVector swdown, Rcpp::NumericVector difrad, Rcpp::NumericVector lwdown, Rcpp::NumericVector windspeed, Rcpp::NumericVector winddir, Rcpp::NumericVector precip, Rcpp::List vegp, Rcpp::List soilc, double Lfrac, double lat, double lon, double zref, double reqhgt, double Ca, double matemp, double zAbove, int maxIter, double tolerance, bool pooling, double slope, double aspect, double svfa, Rcpp::NumericVector shelterc, Rcpp::NumericVector Tinit, Rcpp::NumericVector thetainit);
RcppExport SEXP _microclimf_BigLeafCpp(SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP, SEXP hourSEXP, SEXP tempSEXP, SEXP relhumSEXP, SEXP presSEXP, SEXP swdownSEXP, SEXP difradSEXP, SEXP lwdownSEXP, SEXP windspeedSEXP, SEXP winddirSEXP, SEXP precipSEXP, SEXP vegpSEXP, SEXP soilcSEXP, SEXP LfracSEXP, SEXP latSEXP, SEXP lonSEXP, SEXP zrefSEXP, SEXP reqhgtSEXP, SEXP CaSEXP, SEXP matempSEXP, SEXP zAboveSEXP, SEXP maxIterSEXP, SEXP toleranceSEXP, SEXP poolingSEXP, SEXP slopeSEXP, SEXP aspectSEXP, SEXP svfaSEXP, SEXP sheltercSEXP, SEXP TinitSEXP, SEXP thetainitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type year(yearSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type month(monthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type day(daySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hour(hourSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type relhum(relhumSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pres(presSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type swdown(swdownSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type difrad(difradSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lwdown(lwdownSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type windspeed(windspeedSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type winddir(winddirSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type precip(precipSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type vegp(vegpSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type soilc(soilcSEXP);
    Rcpp::traits::input_parameter< double >::type Lfrac(LfracSEXP);
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< double >::type zref(zrefSEXP);
    Rcpp::traits::input_parameter< double >::type reqhgt(reqhgtSEXP);
    Rcpp::traits::input_parameter< double >::type Ca(CaSEXP);
    Rcpp::traits::input_parameter< double >::type matemp(matempSEXP);
    Rcpp::traits::input_parameter< double >::type zAbove(zAboveSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< bool >::type pooling(poolingSEXP);
    Rcpp::traits::input_parameter< double >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< double >::type aspect(aspectSEXP);
    Rcpp::traits::input_parameter< double >::type svfa(svfaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type shelterc(sheltercSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Tinit(TinitSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type thetainit(thetainitSEXP);
    rcpp_result_gen = Rcpp::wrap(BigLeafCpp(year, month, day, hour, temp, relhum, pres, swdown, difrad, lwdown, windspeed, winddir, precip, vegp, soilc, Lfrac, lat, lon, zref, reqhgt, Ca, matemp, zAbove, maxIter, tolerance, pooling, slope, aspect, svfa, shelterc, Tinit, thetainit));
    return rcpp_result_gen;
END_RCPP
}
// satvapCpp
double satvapCpp(double tc);
RcppExport SEXP _microclimf_satvapCpp(SEXP tcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tc(tcSEXP);
    rcpp_result_gen = Rcpp::wrap(satvapCpp(tc));
    return rcpp_result_gen;
END_RCPP
}
// geometricCpp
std::vector<double> geometricCpp(int n, double totalDepth);
RcppExport SEXP _microclimf_geometricCpp(SEXP nSEXP, SEXP totalDepthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type totalDepth(totalDepthSEXP);
    rcpp_result_gen = Rcpp::wrap(geometricCpp(n, totalDepth));
    return rcpp_result_gen;
END_RCPP
}
// fillNAIDWCpp
std::vector<double> fillNAIDWCpp(std::vector<double> data, int nrow, int ncol, int ntime, std::vector<double> landMask);
RcppExport SEXP _microclimf_fillNAIDWCpp(SEXP dataSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP ntimeSEXP, SEXP landMaskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type ntime(ntimeSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type landMask(landMaskSEXP);
    rcpp_result_gen = Rcpp::wrap(fillNAIDWCpp(data, nrow, ncol, ntime, landMask));
    return rcpp_result_gen;
END_RCPP
}
// zeroplanedisCpp
Rcpp::NumericVector zeroplanedisCpp(Rcpp::NumericVector h, Rcpp::NumericVector pai);
RcppExport SEXP _microclimf_zeroplanedisCpp(SEXP hSEXP, SEXP paiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pai(paiSEXP);
    rcpp_result_gen = Rcpp::wrap(zeroplanedisCpp(h, pai));
    return rcpp_result_gen;
END_RCPP
}
// roughlengthCpp
Rcpp::NumericVector roughlengthCpp(Rcpp::NumericVector h, Rcpp::NumericVector pai, Rcpp::NumericVector d);
RcppExport SEXP _microclimf_roughlengthCpp(SEXP hSEXP, SEXP paiSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(roughlengthCpp(h, pai, d));
    return rcpp_result_gen;
END_RCPP
}
// rslClearHeightCpp
Rcpp::NumericVector rslClearHeightCpp(Rcpp::NumericVector h, Rcpp::NumericVector pai);
RcppExport SEXP _microclimf_rslClearHeightCpp(SEXP hSEXP, SEXP paiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pai(paiSEXP);
    rcpp_result_gen = Rcpp::wrap(rslClearHeightCpp(h, pai));
    return rcpp_result_gen;
END_RCPP
}
// scalarRoughlengthCpp
double scalarRoughlengthCpp(double h, double pai, double d);
RcppExport SEXP _microclimf_scalarRoughlengthCpp(SEXP hSEXP, SEXP paiSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(scalarRoughlengthCpp(h, pai, d));
    return rcpp_result_gen;
END_RCPP
}
// sublayerInfluenceCpp
double sublayerInfluenceCpp(double c);
RcppExport SEXP _microclimf_sublayerInfluenceCpp(SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(sublayerInfluenceCpp(c));
    return rcpp_result_gen;
END_RCPP
}
// momentumInfluenceCpp
double momentumInfluenceCpp(double pai);
RcppExport SEXP _microclimf_momentumInfluenceCpp(SEXP paiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type pai(paiSEXP);
    rcpp_result_gen = Rcpp::wrap(momentumInfluenceCpp(pai));
    return rcpp_result_gen;
END_RCPP
}
// columnResistCpp
double columnResistCpp(double h, double pai, double d, double uf, double LL, double z);
RcppExport SEXP _microclimf_columnResistCpp(SEXP hSEXP, SEXP paiSEXP, SEXP dSEXP, SEXP ufSEXP, SEXP LLSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type uf(ufSEXP);
    Rcpp::traits::input_parameter< double >::type LL(LLSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(columnResistCpp(h, pai, d, uf, LL, z));
    return rcpp_result_gen;
END_RCPP
}
// columnDiffusivityCpp
double columnDiffusivityCpp(double h, double pai, double d, double uf, double LL, double z);
RcppExport SEXP _microclimf_columnDiffusivityCpp(SEXP hSEXP, SEXP paiSEXP, SEXP dSEXP, SEXP ufSEXP, SEXP LLSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type uf(ufSEXP);
    Rcpp::traits::input_parameter< double >::type LL(LLSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(columnDiffusivityCpp(h, pai, d, uf, LL, z));
    return rcpp_result_gen;
END_RCPP
}
// columnUniformRiseResistCpp
double columnUniformRiseResistCpp(double h, double pai, double d, double uf, double LL, double z);
RcppExport SEXP _microclimf_columnUniformRiseResistCpp(SEXP hSEXP, SEXP paiSEXP, SEXP dSEXP, SEXP ufSEXP, SEXP LLSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type uf(ufSEXP);
    Rcpp::traits::input_parameter< double >::type LL(LLSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(columnUniformRiseResistCpp(h, pai, d, uf, LL, z));
    return rcpp_result_gen;
END_RCPP
}
// columnProfileShapeCpp
std::vector<double> columnProfileShapeCpp(double h, double pai, double d, double z);
RcppExport SEXP _microclimf_columnProfileShapeCpp(SEXP hSEXP, SEXP paiSEXP, SEXP dSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(columnProfileShapeCpp(h, pai, d, z));
    return rcpp_result_gen;
END_RCPP
}
// columnHandoverCpp
double columnHandoverCpp(double h, double pai, double d, double uf, double LL);
RcppExport SEXP _microclimf_columnHandoverCpp(SEXP hSEXP, SEXP paiSEXP, SEXP dSEXP, SEXP ufSEXP, SEXP LLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type uf(ufSEXP);
    Rcpp::traits::input_parameter< double >::type LL(LLSEXP);
    rcpp_result_gen = Rcpp::wrap(columnHandoverCpp(h, pai, d, uf, LL));
    return rcpp_result_gen;
END_RCPP
}
// columnGeometryCpp
std::vector<double> columnGeometryCpp(double h, double pai, double d, double LL);
RcppExport SEXP _microclimf_columnGeometryCpp(SEXP hSEXP, SEXP paiSEXP, SEXP dSEXP, SEXP LLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type LL(LLSEXP);
    rcpp_result_gen = Rcpp::wrap(columnGeometryCpp(h, pai, d, LL));
    return rcpp_result_gen;
END_RCPP
}
// phihStarCpp
double phihStarCpp(double ze);
RcppExport SEXP _microclimf_phihStarCpp(SEXP zeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type ze(zeSEXP);
    rcpp_result_gen = Rcpp::wrap(phihStarCpp(ze));
    return rcpp_result_gen;
END_RCPP
}
// dpsihTestCpp
double dpsihTestCpp(double ze);
RcppExport SEXP _microclimf_dpsihTestCpp(SEXP zeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type ze(zeSEXP);
    rcpp_result_gen = Rcpp::wrap(dpsihTestCpp(ze));
    return rcpp_result_gen;
END_RCPP
}
// zeroBareVegCpp
Rcpp::List zeroBareVegCpp(Rcpp::NumericMatrix hgt, Rcpp::NumericMatrix pai, bool countOnly);
RcppExport SEXP _microclimf_zeroBareVegCpp(SEXP hgtSEXP, SEXP paiSEXP, SEXP countOnlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type hgt(hgtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< bool >::type countOnly(countOnlySEXP);
    rcpp_result_gen = Rcpp::wrap(zeroBareVegCpp(hgt, pai, countOnly));
    return rcpp_result_gen;
END_RCPP
}
// matchStructureCpp
Rcpp::List matchStructureCpp(Rcpp::NumericMatrix hgt, Rcpp::NumericMatrix pai, Rcpp::NumericMatrix x, Rcpp::LogicalVector skip, Rcpp::NumericVector refh, Rcpp::NumericVector refpai, Rcpp::NumericVector refx);
RcppExport SEXP _microclimf_matchStructureCpp(SEXP hgtSEXP, SEXP paiSEXP, SEXP xSEXP, SEXP skipSEXP, SEXP refhSEXP, SEXP refpaiSEXP, SEXP refxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type hgt(hgtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type refh(refhSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type refpai(refpaiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type refx(refxSEXP);
    rcpp_result_gen = Rcpp::wrap(matchStructureCpp(hgt, pai, x, skip, refh, refpai, refx));
    return rcpp_result_gen;
END_RCPP
}
// fillByTypeCpp
Rcpp::List fillByTypeCpp(Rcpp::NumericMatrix v, Rcpp::IntegerVector type, Rcpp::NumericVector byType);
RcppExport SEXP _microclimf_fillByTypeCpp(SEXP vSEXP, SEXP typeSEXP, SEXP byTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type byType(byTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(fillByTypeCpp(v, type, byType));
    return rcpp_result_gen;
END_RCPP
}
// rowAnyPositiveCpp
Rcpp::LogicalVector rowAnyPositiveCpp(Rcpp::NumericMatrix v);
RcppExport SEXP _microclimf_rowAnyPositiveCpp(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(rowAnyPositiveCpp(v));
    return rcpp_result_gen;
END_RCPP
}
// maxClearHeightCpp
double maxClearHeightCpp(Rcpp::NumericMatrix hgt, Rcpp::NumericMatrix pai);
RcppExport SEXP _microclimf_maxClearHeightCpp(SEXP hgtSEXP, SEXP paiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type hgt(hgtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pai(paiSEXP);
    rcpp_result_gen = Rcpp::wrap(maxClearHeightCpp(hgt, pai));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_microclimf_runbioclimCpp", (DL_FUNC) &_microclimf_runbioclimCpp, 7},
    {"_microclimf_runmicro1Cpp", (DL_FUNC) &_microclimf_runmicro1Cpp, 13},
    {"_microclimf_dampingDepthGridCpp", (DL_FUNC) &_microclimf_dampingDepthGridCpp, 10},
    {"_microclimf_soilWaterPotentialGridCpp", (DL_FUNC) &_microclimf_soilWaterPotentialGridCpp, 4},
    {"_microclimf_surfaceResistGridCpp", (DL_FUNC) &_microclimf_surfaceResistGridCpp, 6},
    {"_microclimf_referenceGroundResistCpp", (DL_FUNC) &_microclimf_referenceGroundResistCpp, 8},
    {"_microclimf_soilmDistributeCpp", (DL_FUNC) &_microclimf_soilmDistributeCpp, 6},
    {"_microclimf_groundHeatFluxCpp", (DL_FUNC) &_microclimf_groundHeatFluxCpp, 44},
    {"_microclimf_belowGroundShortcutCpp", (DL_FUNC) &_microclimf_belowGroundShortcutCpp, 7},
    {"_microclimf_canopyTempCpp", (DL_FUNC) &_microclimf_canopyTempCpp, 10},
    {"_microclimf_leafTempCpp", (DL_FUNC) &_microclimf_leafTempCpp, 24},
    {"_microclimf_longwaveGridCpp", (DL_FUNC) &_microclimf_longwaveGridCpp, 9},
    {"_microclimf_aboveCanopyProfileGridCpp", (DL_FUNC) &_microclimf_aboveCanopyProfileGridCpp, 15},
    {"_microclimf_belowCanopyProfileGridCpp", (DL_FUNC) &_microclimf_belowCanopyProfileGridCpp, 17},
    {"_microclimf_belowCanopyProfilePointCpp", (DL_FUNC) &_microclimf_belowCanopyProfilePointCpp, 17},
    {"_microclimf_computeSolarSeriesRCpp", (DL_FUNC) &_microclimf_computeSolarSeriesRCpp, 6},
    {"_microclimf_radiationPointCpp", (DL_FUNC) &_microclimf_radiationPointCpp, 15},
    {"_microclimf_splineFitCpp", (DL_FUNC) &_microclimf_splineFitCpp, 2},
    {"_microclimf_splineEvalCpp", (DL_FUNC) &_microclimf_splineEvalCpp, 2},
    {"_microclimf_BigLeafCpp", (DL_FUNC) &_microclimf_BigLeafCpp, 32},
    {"_microclimf_satvapCpp", (DL_FUNC) &_microclimf_satvapCpp, 1},
    {"_microclimf_geometricCpp", (DL_FUNC) &_microclimf_geometricCpp, 2},
    {"_microclimf_fillNAIDWCpp", (DL_FUNC) &_microclimf_fillNAIDWCpp, 5},
    {"_microclimf_zeroplanedisCpp", (DL_FUNC) &_microclimf_zeroplanedisCpp, 2},
    {"_microclimf_roughlengthCpp", (DL_FUNC) &_microclimf_roughlengthCpp, 3},
    {"_microclimf_rslClearHeightCpp", (DL_FUNC) &_microclimf_rslClearHeightCpp, 2},
    {"_microclimf_scalarRoughlengthCpp", (DL_FUNC) &_microclimf_scalarRoughlengthCpp, 3},
    {"_microclimf_sublayerInfluenceCpp", (DL_FUNC) &_microclimf_sublayerInfluenceCpp, 1},
    {"_microclimf_momentumInfluenceCpp", (DL_FUNC) &_microclimf_momentumInfluenceCpp, 1},
    {"_microclimf_columnResistCpp", (DL_FUNC) &_microclimf_columnResistCpp, 6},
    {"_microclimf_columnDiffusivityCpp", (DL_FUNC) &_microclimf_columnDiffusivityCpp, 6},
    {"_microclimf_columnUniformRiseResistCpp", (DL_FUNC) &_microclimf_columnUniformRiseResistCpp, 6},
    {"_microclimf_columnProfileShapeCpp", (DL_FUNC) &_microclimf_columnProfileShapeCpp, 4},
    {"_microclimf_columnHandoverCpp", (DL_FUNC) &_microclimf_columnHandoverCpp, 5},
    {"_microclimf_columnGeometryCpp", (DL_FUNC) &_microclimf_columnGeometryCpp, 4},
    {"_microclimf_phihStarCpp", (DL_FUNC) &_microclimf_phihStarCpp, 1},
    {"_microclimf_dpsihTestCpp", (DL_FUNC) &_microclimf_dpsihTestCpp, 1},
    {"_microclimf_zeroBareVegCpp", (DL_FUNC) &_microclimf_zeroBareVegCpp, 3},
    {"_microclimf_matchStructureCpp", (DL_FUNC) &_microclimf_matchStructureCpp, 7},
    {"_microclimf_fillByTypeCpp", (DL_FUNC) &_microclimf_fillByTypeCpp, 3},
    {"_microclimf_rowAnyPositiveCpp", (DL_FUNC) &_microclimf_rowAnyPositiveCpp, 1},
    {"_microclimf_maxClearHeightCpp", (DL_FUNC) &_microclimf_maxClearHeightCpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_microclimf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
