# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runbioclimCpp <- function(Tz, soilm, out, wetq, dryq, hotq, colq) {
    .Call(`_microclimf_runbioclimCpp`, Tz, soilm, out, wetq, dryq, hotq, colq)
}

runmicro1Cpp <- function(obstime, climdata, vegp, soilc, lats, lons, zref, z, ufRef, HRef, dRef, zmRef, shelterc) {
    .Call(`_microclimf_runmicro1Cpp`, obstime, climdata, vegp, soilc, lats, lons, zref, z, ufRef, HRef, dRef, zmRef, shelterc)
}

dampingDepthGridCpp <- function(Vq, Vm, Vo, Mc, thetaS, psie, b, soilm, Ts, pk) {
    .Call(`_microclimf_dampingDepthGridCpp`, Vq, Vm, Vo, Mc, thetaS, psie, b, soilm, Ts, pk)
}

soilWaterPotentialGridCpp <- function(thetaS, psie, b, soilm) {
    .Call(`_microclimf_soilWaterPotentialGridCpp`, thetaS, psie, b, soilm)
}

surfaceResistGridCpp <- function(rad, clim, soilm, soil, veg, ref) {
    .Call(`_microclimf_surfaceResistGridCpp`, rad, clim, soilm, soil, veg, ref)
}

referenceGroundResistCpp <- function(uref, ufRef, HRef, Ta, pk, zref, hRef, paiRef) {
    .Call(`_microclimf_referenceGroundResistCpp`, uref, ufRef, HRef, Ta, pk, zref, hRef, paiRef)
}

soilmDistributeCpp <- function(Smin, Smax, tadd, wet, theta0, tsteps) {
    .Call(`_microclimf_soilmDistributeCpp`, Smin, Smax, tadd, wet, theta0, tsteps)
}

groundHeatFluxCpp <- function(RabsGround, rGz, rGm, RabsCanopy, rHa, rSurf_ref, hSurf_ref, hFol_ref, soilm, Ta, rh, pk, Vq, Vm, Vo, Mc, thetaS, psie, b, svfa, emGround, emCanopy, slope, aspect, Rsw, Rdif, lats, lons, year, month, day, hour, G_ref, RabsGround_ref, rGz_ref, theta0_ref, emGround_ref, VqRef, VmRef, VoRef, McRef, thetaSRef, psieRef, bRef) {
    .Call(`_microclimf_groundHeatFluxCpp`, RabsGround, rGz, rGm, RabsCanopy, rHa, rSurf_ref, hSurf_ref, hFol_ref, soilm, Ta, rh, pk, Vq, Vm, Vo, Mc, thetaS, psie, b, svfa, emGround, emCanopy, slope, aspect, Rsw, Rdif, lats, lons, year, month, day, hour, G_ref, RabsGround_ref, rGz_ref, theta0_ref, emGround_ref, VqRef, VmRef, VoRef, McRef, thetaSRef, psieRef, bRef)
}

belowGroundShortcutCpp <- function(Ts_est, Tgp_ref, Tbp_ref, DD, mat, reqhgt, hiy = 8760.0) {
    .Call(`_microclimf_belowGroundShortcutCpp`, Ts_est, Tgp_ref, Tbp_ref, DD, mat, reqhgt, hiy)
}

canopyTempCpp <- function(RabsCanopy, rHa, G_est, Ta, rh, pk, svfa, emCanopy, rSurf_ref, hSurf_ref) {
    .Call(`_microclimf_canopyTempCpp`, RabsCanopy, rHa, G_est, Ta, rh, pk, svfa, emCanopy, rSurf_ref, hSurf_ref)
}

leafTempCpp <- function(radLpar, radLsw, radLlw, uz, Ta, rh, pk, Ca, psi_r, hgt, pai, Vcmax25, Tup, Tlw, Dcrit, alpha, f0, fd, psi50, apsi, rpmin, leafd, isC3, reqhgt) {
    .Call(`_microclimf_leafTempCpp`, radLpar, radLsw, radLlw, uz, Ta, rh, pk, Ca, psi_r, hgt, pai, Vcmax25, Tup, Tlw, Dcrit, alpha, f0, fd, psi50, apsi, rpmin, leafd, isC3, reqhgt)
}

longwaveGridCpp <- function(Ts_est, Tcanopy_est, Ta, hgt, pai, paia, svfa, lwdown, reqhgt) {
    .Call(`_microclimf_longwaveGridCpp`, Ts_est, Tcanopy_est, Ta, hgt, pai, paia, svfa, lwdown, reqhgt)
}

aboveCanopyProfileGridCpp <- function(Tcanopy_est, rHa, L, uf, d, zh, Ta, rh, rSurf_ref, hSurf_ref, rGz, rGreq, zs, reqhgt, zref) {
    .Call(`_microclimf_aboveCanopyProfileGridCpp`, Tcanopy_est, rHa, L, uf, d, zh, Ta, rh, rSurf_ref, hSurf_ref, rGz, rGreq, zs, reqhgt, zref)
}

belowCanopyProfileGridCpp <- function(Tcanopy_est, Ts_est, rBL, rGh, rGm, rGz, shapeR, shapeC, hgtCell, paiCell, Ta, rh, pk, rSurf_ref, hSurf_ref, reqhgt, zref) {
    .Call(`_microclimf_belowCanopyProfileGridCpp`, Tcanopy_est, Ts_est, rBL, rGh, rGm, rGz, shapeR, shapeC, hgtCell, paiCell, Ta, rh, pk, rSurf_ref, hSurf_ref, reqhgt, zref)
}

belowCanopyProfilePointCpp <- function(Tcanopy, Tground, groundhr, rBL, L, uf, d, zm, hgt, pai, Ta, rh, pk, rSurf, hSurf, reqhgt, zref) {
    .Call(`_microclimf_belowCanopyProfilePointCpp`, Tcanopy, Tground, groundhr, rBL, L, uf, d, zm, hgt, pai, Ta, rh, pk, rSurf, hSurf, reqhgt, zref)
}

computeSolarSeriesRCpp <- function(lat, lon, year, month, day, hour) {
    .Call(`_microclimf_computeSolarSeriesRCpp`, lat, lon, year, month, day, hour)
}

radiationPointCpp <- function(pai, paia, x, lref, ltra, clump, gref, svfa, slope, aspect, zend, azid, shadow, Rsw, Rdif) {
    .Call(`_microclimf_radiationPointCpp`, pai, paia, x, lref, ltra, clump, gref, svfa, slope, aspect, zend, azid, shadow, Rsw, Rdif)
}

splineFitCpp <- function(knotX, knotY) {
    .Call(`_microclimf_splineFitCpp`, knotX, knotY)
}

splineEvalCpp <- function(fit, queryX) {
    .Call(`_microclimf_splineEvalCpp`, fit, queryX)
}

BigLeafCpp <- function(year, month, day, hour, temp, relhum, pres, swdown, difrad, lwdown, windspeed, winddir, precip, vegp, soilc, Lfrac, lat, lon, zref, reqhgt = NA_real_, Ca = 400.0, matemp = NA_real_, zAbove = NA_real_, maxIter = 100L, tolerance = 1e-2, pooling = FALSE, slope = 0.0, aspect = 0.0, svfa = 1.0, shelterc = as.numeric( c(1.0)), Tinit = as.numeric( c()), thetainit = as.numeric( c())) {
    .Call(`_microclimf_BigLeafCpp`, year, month, day, hour, temp, relhum, pres, swdown, difrad, lwdown, windspeed, winddir, precip, vegp, soilc, Lfrac, lat, lon, zref, reqhgt, Ca, matemp, zAbove, maxIter, tolerance, pooling, slope, aspect, svfa, shelterc, Tinit, thetainit)
}

satvapCpp <- function(tc) {
    .Call(`_microclimf_satvapCpp`, tc)
}

geometricCpp <- function(n, totalDepth) {
    .Call(`_microclimf_geometricCpp`, n, totalDepth)
}

fillNAIDWCpp <- function(data, nrow, ncol, ntime, landMask) {
    .Call(`_microclimf_fillNAIDWCpp`, data, nrow, ncol, ntime, landMask)
}

zeroplanedisCpp <- function(h, pai) {
    .Call(`_microclimf_zeroplanedisCpp`, h, pai)
}

roughlengthCpp <- function(h, pai, d) {
    .Call(`_microclimf_roughlengthCpp`, h, pai, d)
}

rslClearHeightCpp <- function(h, pai) {
    .Call(`_microclimf_rslClearHeightCpp`, h, pai)
}

scalarRoughlengthCpp <- function(h, pai, d) {
    .Call(`_microclimf_scalarRoughlengthCpp`, h, pai, d)
}

sublayerInfluenceCpp <- function(c) {
    .Call(`_microclimf_sublayerInfluenceCpp`, c)
}

momentumInfluenceCpp <- function(pai) {
    .Call(`_microclimf_momentumInfluenceCpp`, pai)
}

columnResistCpp <- function(h, pai, d, uf, LL, z) {
    .Call(`_microclimf_columnResistCpp`, h, pai, d, uf, LL, z)
}

columnDiffusivityCpp <- function(h, pai, d, uf, LL, z) {
    .Call(`_microclimf_columnDiffusivityCpp`, h, pai, d, uf, LL, z)
}

columnUniformRiseResistCpp <- function(h, pai, d, uf, LL, z) {
    .Call(`_microclimf_columnUniformRiseResistCpp`, h, pai, d, uf, LL, z)
}

columnProfileShapeCpp <- function(h, pai, d, z) {
    .Call(`_microclimf_columnProfileShapeCpp`, h, pai, d, z)
}

columnHandoverCpp <- function(h, pai, d, uf, LL) {
    .Call(`_microclimf_columnHandoverCpp`, h, pai, d, uf, LL)
}

columnGeometryCpp <- function(h, pai, d, LL) {
    .Call(`_microclimf_columnGeometryCpp`, h, pai, d, LL)
}

phihStarCpp <- function(ze) {
    .Call(`_microclimf_phihStarCpp`, ze)
}

dpsihTestCpp <- function(ze) {
    .Call(`_microclimf_dpsihTestCpp`, ze)
}

zeroBareVegCpp <- function(hgt, pai, countOnly = FALSE) {
    .Call(`_microclimf_zeroBareVegCpp`, hgt, pai, countOnly)
}

matchStructureCpp <- function(hgt, pai, x, skip, refh, refpai, refx) {
    .Call(`_microclimf_matchStructureCpp`, hgt, pai, x, skip, refh, refpai, refx)
}

fillByTypeCpp <- function(v, type, byType) {
    .Call(`_microclimf_fillByTypeCpp`, v, type, byType)
}

rowAnyPositiveCpp <- function(v) {
    .Call(`_microclimf_rowAnyPositiveCpp`, v)
}

maxClearHeightCpp <- function(hgt, pai) {
    .Call(`_microclimf_maxClearHeightCpp`, hgt, pai)
}

